# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          docker login -u=${{ secrets.JFROG_USER_WRITER }} -p=${{ secrets.JFROG_PASSWORD_WRITER }}
          docker build .
          docker build -t det-docker.artifactory.comcast.com/gheactions:latest .
          docker push det-docker.artifactory.comcast.com/gheactions:latest
          wget https://artifactory.comcast.com/artifactory/centos/filelist.gz
          touch 22223
     
